USE [master]
GO
/****** Objeto:  Database [RevisaoMVC]    Data do Script: 17/09/2026 07:55:24 ******/
CREATE DATABASE [RevisaoMVC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RevisaoMVC', FILENAME = N'C:\Users\47786092803\RevisaoMVC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RevisaoMVC_log', FILENAME = N'C:\Users\47786092803\RevisaoMVC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RevisaoMVC] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RevisaoMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RevisaoMVC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ARITHABORT OFF 
GO
ALTER DATABASE [RevisaoMVC] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [RevisaoMVC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RevisaoMVC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RevisaoMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RevisaoMVC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RevisaoMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RevisaoMVC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RevisaoMVC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RevisaoMVC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RevisaoMVC] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RevisaoMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RevisaoMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RevisaoMVC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RevisaoMVC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RevisaoMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RevisaoMVC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RevisaoMVC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RevisaoMVC] SET  MULTI_USER 
GO
ALTER DATABASE [RevisaoMVC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RevisaoMVC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RevisaoMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RevisaoMVC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RevisaoMVC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RevisaoMVC] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [RevisaoMVC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RevisaoMVC] SET QUERY_STORE = ON
GO
ALTER DATABASE [RevisaoMVC] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RevisaoMVC]
GO
/****** Objeto:  Table [dbo].[Livro]    Data do Script: 17/09/2026 07:55:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Livro](
	[IdLivro] [int] IDENTITY(1,1) NOT NULL,
	[NomeLivro] [nvarchar](120) NOT NULL,
	[Descricao] [nvarchar](500) NOT NULL,
	[DataLivro] [date] NOT NULL,
	[Foto] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdLivro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto:  Table [dbo].[Usuarios]    Data do Script: 17/09/2026 07:55:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[IdUsario] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](40) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[Senha] [varbinary](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Livro] ON 
GO
INSERT [dbo].[Livro] ([IdLivro], [NomeLivro], [Descricao], [DataLivro], [Foto]) VALUES (1, N'Harry Potter', N'Livro de bruxaria', CAST(N'2010-01-01' AS Date), NULL)
GO
SET IDENTITY_INSERT [dbo].[Livro] OFF
GO
SET IDENTITY_INSERT [dbo].[Usuarios] ON 
GO
INSERT [dbo].[Usuarios] ([IdUsario], [Nome], [Email], [Senha]) VALUES (1, N'Fulano da Silva', N'fulano@email.com', 0x8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92)
GO
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO
SET ANSI_PADDING ON
GO
/****** Objeto:  Index [UQ__Usuarios__7D8FE3B2005E07A7]    Data do Script: 17/09/2026 07:55:24 ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Objeto:  Index [UQ__Usuarios__A9D105340B04A4AE]    Data do Script: 17/09/2026 07:55:24 ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RevisaoMVC] SET  READ_WRITE 
GO
